name: Node.js Package

on:
  push:
    tags:
      - '*'

jobs:
  publish-gpr:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://npm.pkg.github.com/
      - run: npm ci
      - run: |
          TAG=$(echo $TAG_NAME | cut -d'/' -f3)
          npx nx run-many -t publish --ver $TAG --tag latest
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
          TAG_NAME: ${{ github.ref }}